language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: fbacf87de301787c48ea6782bd21e392af3d75c6
  local-dir: book
  keep-history: false
  on:
    branch: master
