language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: e9539dfbd4a7617aacdf2c2ff9af64a3db05b9f2
  local-dir: book
  keep-history: false
  on:
    branch: master
